language: python
python:
  - '3.6'
install:
  - pip install nose twine
script:
  - "./setup.py build sdist"
  - twine check dist/*
  - pip install .
  - nosetests
deploy:
  provider: pypi
  user: pfariello
  password:
    secure: B7J/EHkb8Zif81oyu3hb804DBupJ4iKnyUWqNCreDl2xnXPr3G+bLYTDL2yAMYw7YPA50PWqe97Q9VC4q2va0BiqpFMhMMQYzmtWGX2Enr3QWwoVfrjS8GcS2tIZrtGiez6Hqh81lulr9eob9x7Yc8Sq3c94by3JHI8tnTP0LAR4SikLyRUd2HajDBgVbfzSsbWYBgARVtWiiMHGL74Wz5ODbqh0sgEIUUym3Cs1I7bbnC88iYorG+0Y2uD2fv3AluEnEG0m/xWn+dzxVgCqPhecOp9DTfep4h8NBY6ND1mPznrT6wpTwZIfF8RM+4Pkj+cqrDqgD9CesE9pWLNTBJ1WbqW1F050fZ/9HIHgrKwKQJOthK9m9gsbq/Hh683kg9y9J9CcxHSjfzqu450ckUbp2bEyIbANzL5ZhjvuDJXfD0P+U7oTzWFBw7fmeUrqLbP5esPX2Ch2yvr5MQuIYXqicLwy3KnoHoScV9ADGJe8Nu37AuCIQwA+CFqHZRenVcHtclzDg6KLESIuHdS3XGh+SITT1xyWnzvjPUKNus2jvKi3oUflG4/XKHiODZQOvPYxrzHw2DKCBBnsKuSjfiZSc9VRxk4f8jx+VHSDOHNrHZBrDW8sUvG+H2YZqW1aPklTJ7Sz+KDlFQ9GKViGVFl2ohZItv1BYUJa47ZIlzQ=
  on:
    tags: true
    python: '3.6'
  skip_existing: true
